title: "IRENGE JOEL BAHAGARHE"
logo: /assets/img/
description: "A portfolio showcasing my AI-based models project  and other project, 
"
show_downloads: true
theme: jekyll-theme-Midnight
google_analytics: UA-XXXXX-Y

