title: "Joel's AI Projects Portfolio"
description: "A portfolio showcasing my AI-based models and project, including image generation, and various tech projects."
show_downloads: true
theme: jekyll-theme-Midnight
google_analytics: UA-XXXXX-Y

